apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  chart:
    spec:
      chart: rancher
      version: 2.x.x
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: rancher
  valuesFrom:
  - kind: ConfigMap
    name: rancher-helm-chart-value-overrides
    valuesKey: values.yaml # (1)! This is the default, but best to be explicit for clarity
